# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name unique_vector
#' @noRd
#'
NULL

#' @name set_diff
#' @noRd
#'
NULL

#' @name c_basis2
#' @title CB construction
#' @description The SVD-based constraint basis construction for non-overlapping
#' subsets of constraints. Algorithm 1 from the reference.
#' Creating a basis from the matrix A
#' @param A `nxk matrix` must have rank k
#' @param eps_limit `double` used as a limit of small value
#' @return T (n x n) the basis matrix
#' @noRd
#'
c_basis2 <- function(A, eps_limit = 1e-10) {
    .Call(`_MetricGraph_c_basis2`, A, eps_limit)
}

construct_constraint_matrix <- function(E, nV, edge_constraint) {
    .Call(`_MetricGraph_construct_constraint_matrix`, E, nV, edge_constraint)
}

construct_directional_constraint_matrix <- function(E, nV, nE, alpha, V_indegree, V_outdegree) {
    .Call(`_MetricGraph_construct_directional_constraint_matrix`, E, nV, nE, alpha, V_indegree, V_outdegree)
}

#' @name proj_vec
#' @noRd
NULL

#' @name proj_vec2
#' @noRd
NULL

#' @name proj_vec
#' @noRd
NULL

#' @name proj_vec_line
#' @noRd
NULL

#' @name assemble_fem
#' @title Construction of FEM matrices
#' @description Function used to construct FEM matrices on metric graphs.
#' @param E `nx2 matrix` Matrix of edges
#' @param h_e `n vector` Vector of h's
#' @param nV `int` Number of vertices
#' @noRd
#'
assemble_fem <- function(E, h_e, nV, petrov) {
    .Call(`_MetricGraph_assemble_fem`, E, h_e, nV, petrov)
}

#' @name compute_mesh_weights
#' @title Compute the weights of the mesh nodes
#' @description Function used to compute the weights of the mesh nodes on metric graphs.
#' @param E `nx2 matrix` Matrix of edges
#' @param h_e `n vector` Vector of h's
#' @param nV `int` Number of vertices.
#' @noRd
#'
compute_mesh_weights <- function(E, h_e, nV) {
    .Call(`_MetricGraph_compute_mesh_weights`, E, h_e, nV)
}

#' @name projectVecLine
#' @title Projects SpatialPoints into SpatialLines
#' @description Obtain the coordinates of the projection of points into lines.
#' @param lines `nx2 matrix` Matrix of the points of the lines
#' @param points `nx2 matrix` Matrix of the points
#' @param normalized `int` 0 means not normalized, 1 means normalized
#' @noRd
#'
projectVecLine <- function(lines, points, normalized = 0L) {
    .Call(`_MetricGraph_projectVecLine`, lines, points, normalized)
}

#' @name interpolate2
#' @title Finds the point with respect to a distance along the line
#' @description Finds the point with respect to a distance along the line
#' @param lines `nx2 matrix` Matrix of the points of the lines
#' @param pos `k vector` vector of positions.
#' @param normalized `int` 0 means not normalized, 1 means normalized
#' @noRd
#'
interpolate2_aux <- function(lines, pos, normalized = 0L) {
    .Call(`_MetricGraph_interpolate2_aux`, lines, pos, normalized)
}

#' @name compute_length
#' @title Compute length
#' @description Computes the length of a piecewise-linear function whose coordinates are given in a matrix.
#' The function expects coordinates with at least 2 columns (x, y). If more columns are provided,
#' only the first two columns (x, y) are used for the calculation.
#' @param coords nxk matrix Matrix of the points of the lines (k >= 2, typically nx2)
#' @noRd
#'
compute_length <- function(coords) {
    .Call(`_MetricGraph_compute_length`, coords)
}

generate_mesh <- function(n_edges, edge_lengths, n_e, E, ind, continuous) {
    .Call(`_MetricGraph_generate_mesh`, n_edges, edge_lengths, n_e, E, ind, continuous)
}

#' @name PtE_to_mesh_cpp
#' @title Convert PtE for mesh given PtE for graph
#' @description C++ implementation of PtE_to_mesh function
#' @param PtE `nx2 matrix` Matrix with edge indices and positions
#' @param VtE `nx2 matrix` Matrix from VtEfirst()
#' @param mesh_PtE `nx2 matrix` Mesh PtE matrix
#' @param E `nx2 matrix` Graph edge matrix
#' @param mesh_E `nx2 matrix` Mesh edge matrix
#' @param edge_lengths `n vector` Vector of edge lengths
#' @param mesh_h_e `n vector` Vector of mesh edge lengths
#' @param nV `int` Number of vertices
#' @noRd
#'
PtE_to_mesh_cpp <- function(PtE, VtE, mesh_PtE, E, mesh_E, edge_lengths, mesh_h_e, nV) {
    .Call(`_MetricGraph_PtE_to_mesh_cpp`, PtE, VtE, mesh_PtE, E, mesh_E, edge_lengths, mesh_h_e, nV)
}

#' @name compute_PtE_edges_cpp
#' @title Per-edge cumulative relative positions
#' @description Given a list of edges (each a 2-column numeric matrix of
#' vertex coordinates), compute, for every edge, the cumulative arc-length
#' normalized to lie in [0, 1]. Returns a list of numeric vectors, one per
#' edge, each starting at 0 and ending at 1.
#'
#' Degenerate (zero-length) edges return a vector of NaN values, matching
#' the R-side \code{0/0} semantics of the original \code{approx_coordinates}
#' implementation.
#'
#' @param edges List of two-column numeric matrices.
#' @param longlat Logical. If TRUE, use haversine on (lon, lat) in degrees;
#' otherwise use planar Euclidean distances.
#' @return A list of numeric vectors, the same length as \code{edges}.
#' @noRd
compute_PtE_edges_cpp <- function(edges, longlat) {
    .Call(`_MetricGraph_compute_PtE_edges_cpp`, edges, longlat)
}

#' @name compute_edge_lengths_cpp
#' @title Per-edge total polyline lengths
#' @description Given a list of edges (each a 2-column numeric matrix of
#' vertex coordinates), compute the total polyline length of each edge.
#' Returns a numeric vector of length \code{length(edges)}.
#'
#' Replaces a per-edge \code{sapply(self$edges, compute_line_lengths, ...)}
#' that, in the lon/lat case, constructed an \code{sf::st_sfc} linestring
#' object per edge -- ~9000x slower than necessary at OSM scales. The R6
#' caller is responsible for any final unit conversion (km / miles / etc).
#'
#' @param edges List of two-column numeric matrices.
#' @param longlat Logical. If TRUE, treat columns as (lon, lat) in degrees
#' and return lengths in metres (haversine on a sphere of radius
#' 6371008.8 m). If FALSE, return planar Euclidean lengths in whatever
#' coordinate units the edges happen to be in.
#' @return A numeric vector of edge lengths.
#' @noRd
compute_edge_lengths_cpp <- function(edges, longlat) {
    .Call(`_MetricGraph_compute_edge_lengths_cpp`, edges, longlat)
}

#' @name postprocess_edges_cpp
#' @title Dedupe interior polyline points while preserving endpoints
#' @description translation of the post-merge "clean edges"
#' \code{lapply} that the metric_graph constructor runs after the
#' vertex-merge step. For each edge, deduplicates rows by exact
#' \code{(x, y)} equality, while forcing the original first row to remain
#' at position 1 and the original last row to be appended at the end.
#'
#' Linear scan beats hashing here because edges typically have only 2-15
#' points; constant overhead of an unordered_set wins for n > ~50.
#'
#' @param edges List of two-column numeric matrices.
#' @return A list of two-column numeric matrices with deduped interior
#' rows. May have fewer rows than the input.
#' @noRd
postprocess_edges_cpp <- function(edges) {
    .Call(`_MetricGraph_postprocess_edges_cpp`, edges)
}

selected_inv_cpp <- function(Q) {
    .Call(`_MetricGraph_selected_inv_cpp`, Q)
}

