on:
  push:
    branches:
      - cran

name: cran_setup
  
jobs:
    cran_setup:
      runs-on: ubuntu-20.04
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v2      
        
        - name: Delete vignettes and pkgdown, then copy cran vign
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"          
            mkdir vignettes
            cd cran_vignettes
            cp * ../vignettes
            cd ..
            git rm -rf cran_vignettes
            git add vignettes
            git commit -m "Doing the setup"
            git push
          shell: bash
