on:
  push:
    branches:
      - cran

name: cran_setup

permissions:
  contents: write

jobs:
  cran_setup:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete vignettes, pkgdown, selected tests, then copy cran vign
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git rm -rf --ignore-unmatch vignettes
          git rm -rf --ignore-unmatch pkgdown/
          git rm -f --ignore-unmatch index.md
          git rm -rf --ignore-unmatch examples
          git rm -rf --ignore-unmatch inst/shared

          git rm -f --ignore-unmatch tests/testthat/test_inla_inlabru_interfaces.R
          git rm -f --ignore-unmatch tests/testthat/test_inlabru_predict.R
          git rm -f --ignore-unmatch tests/testthat/test_cgeneric.R
          git rm -f --ignore-unmatch tests/testthat/test_cross_validation.R
          git rm -f --ignore-unmatch tests/testthat/test-prune-vertices-perf.R 
          git rm -f --ignore-unmatch tests/testthat/test-disconnected-models.R
          git rm -f --ignore-unmatch tests/testthat/test-compute-distances.R
          git rm -f --ignore-unmatch tests/testthat/test-cpp-helpers.R 
          git rm -f --ignore-unmatch tests/testthat/test-metric-graph-components.R          
          git rm -f --ignore-unmatch tests/testthat/test-coverage-gaps.R       
          git rm -f --ignore-unmatch tests/testthat/test_random_fields_vignette.R   
          git rm -f --ignore-unmatch tests/testthat/test-observation-to-vertex.R

          rm -rf vignettes
          mkdir -p vignettes

          cp cran_vignettes/* vignettes/

          git rm -rf --ignore-unmatch cran_vignettes

          git add vignettes

          git commit -m "Doing the setup" || echo "No changes to commit"
          git push
        shell: bash