on:
  push:
    branches:
      - devel

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          extra-repositories: "https://inla.r-inla-download.org/R/testing"

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies on MacOS (X11, gdal)
        run: |
          brew install --cask xquartz
          brew install pkg-config
          brew install proj@9
          brew install gdal
          brew install eigen

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: |
             pkgdown
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
      - name: Installing rSPDE
        run: |
          install.packages(c("remotes", "rmarkdown"),dependencies=TRUE)
          remotes::install_github("davidbolin/rSPDE")
        shell: Rscript {0}   
      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
